# Generated by Django 4.0.6 on 2022-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuyendung',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
