# Generated by Django 4.0.6 on 2022-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0002_alter_tuyendung_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuyendung',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
