# Generated by Django 4.0.6 on 2022-07-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuyendung',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuyendung',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
