# Generated by Django 4.0.6 on 2022-07-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0006_tuyendung_end_date_alter_tuyendung_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='where',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuyendung',
            name='where',
        ),
        migrations.AddField(
            model_name='tuyendung',
            name='where_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tuyendung.where'),
        ),
    ]
