# Generated by Django 4.0.6 on 2022-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0007_where_remove_tuyendung_where_tuyendung_where_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuyendung',
            name='where_id',
        ),
        migrations.AddField(
            model_name='tuyendung',
            name='where',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='where',
        ),
    ]
