# Generated by Django 4.0.6 on 2022-07-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuyendung', '0008_remove_tuyendung_where_id_tuyendung_where_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='congviec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tuyendung',
            old_name='link_lk',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='tuyendung',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tuyendung',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuyendung.congviec'),
        ),
    ]
